name = "fantasy-snapshot-week"
main = "snapshot-week.js"
compatibility_date = "2026-01-01"

[triggers]
crons = ["0 14 * * 2"]

[[kv_namespaces]]
binding = "HISTORY_KV"
id = "3c4ba0b7387941aa8dd61444fcf9be39"
